networks:
  default:
    enable_ipv6: false
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

services:
  airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    container_name: airflow_webserver
    restart: always
    depends_on:
      - airflow-scheduler
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=require
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_SSLMODE=require
      - OPENAQ_API_KEY=${OPENAQ_API_KEY}
      - OPENAQ_DEFAULT_START_DATE=${OPENAQ_DEFAULT_START_DATE}
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/plugins:/opt/airflow/plugins
      - ./airflow_db:/opt/airflow
      - ./src:/opt/airflow/src
    ports:
      - "8080:8080"
    command: >
      bash -c "
        airflow db init &&
        airflow users create --username admin --password admin --firstname a --lastname b --role Admin --email admin@example.com &&
        airflow webserver
      "

  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    container_name: airflow_scheduler
    restart: always
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=require
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_SSLMODE=require
      - OPENAQ_API_KEY=${OPENAQ_API_KEY}
      - OPENAQ_DEFAULT_START_DATE=${OPENAQ_DEFAULT_START_DATE}
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/plugins:/opt/airflow/plugins
      - ./airflow_db:/opt/airflow
      - ./src:/opt/airflow/src
    command: >
      bash -c "
        airflow scheduler
      "

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_airquality
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@airquality.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_SERVER_JSON_FILE: /pgadmin4/servers.json
      GUNICORN_CMD_ARGS: "--bind=0.0.0.0:80"
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json
      - pgadmin_data:/var/lib/pgadmin

  streamlit-frontend:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: streamlit_frontend
    restart: always
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_SSLMODE=require
    ports:
      - "8501:8501"
    volumes:
      - ./src/frontend:/app
    command: streamlit run /app/app.py --server.port=8501 --server.address=0.0.0.0


volumes:
  pgadmin_data: {}
